### ISSUE TITLE
ship libomp.a and libomp.so

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#51]
both arm64 and x86_64 ship this in `prebuilts/clang/host/linux-x86/clang-r475365/runtimes_ndk_cxx/`

**Comment by appujee** [comment]
cc: @pirama-arumuga-nainar do we need to have libomp in RISC-V?

**Comment by pirama-arumuga-nainar** [comment]
Yes, I think it'd be good to have libomp to ensure compatibility.  This, and other libraries (fuzzer, lldb-server) are explicitly not built because we don't have a minimum NDK API level and a sysroot for that API level.  When we have some clarity, we should add it to https://android.googlesource.com/toolchain/llvm_android/+/205bdc6e08c820afa2c5380d67044db4b2d62825/configs.py#629

**Comment by enh-google** [comment]
prebuilts/clang/host/linux-x86/clang-r498229b/runtimes_ndk_cxx/riscv64 lgtm?

**Comment by appujee** [comment]
yes. https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r498229b/runtimes_ndk_cxx/riscv64/
