### ISSUE TITLE
clang compiler should emit atomic sequences that are compatible with hboehm's suggested new instructions [llvm]

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#73]
hboehm has a plan for better atomic instructions, and that plan includes a forwards-compatible change to the way the compiler emits existing atomic instructions. we should make sure (a) clang implements that and (b) that it's on by default in the compiler driver (at least for android). needed for any NDK.

**Comment by asb** [comment]
#992 is relevant, but I think on the LLVM side we need an agreed and updated mapping table (like table A.6 in the current ISA manual), in order to properly review any patches submitted in this area. It sounds like the preference on the riscv-isa-manual side is to move such an effort outside of the ISA manual and to something like the psABI doc.

**Comment by appujee** [comment]
> like table A.6 in the current ISA manual

This one? Do we have something like this for ARM/X86 in llvm already?

![Screenshot from 2023-04-06 00-16-45](https://user-images.githubusercontent.com/124090381/230302905-f6f2ef89-540e-45a6-81f3-f30d5b18fdda.png)

**Comment by asb** [comment]
That's the one - I didn't mean we need to incorporate that table into LLVM documentation, just that memory models are complicated enough as it is so it would be much better from a review perspective if any patches can be validated against a clear table like this rather than trying to ensure we have a common understanding of a prose description.

As discussed in the linked thread, it sounds like the plan remains to move more of this to the ABI document.

**Comment by appujee** [comment]
After https://github.com/riscv/riscv-isa-manual/pull/992 lands, the table will change a little.

**Comment by appujee** [comment]
The [patch](https://reviews.llvm.org/D149486) hasn't landed in upstream llvm but we are cherry-picking it: https://android-review.googlesource.com/c/toolchain/llvm_android/+/2631670
