### ISSUE TITLE
[Discussion] one question about "libbionic_tests_headers_posix"

### ISSUE THREAD

**Issue by unicornx** [google/android-riscv64#88]
hello, this is a quesiton may not be very related to riscv64, but please allow me post here because I see it is a place where we can discuss some questions in technical ;)

I see "libbionic_tests_headers_posix" in `bionic/tests/headers/posix/Android.bp` and I think it is used to test the posix comptatibility for bonic, but I find "libbionic_tests_headers_posix" is not used by any other target, so my question is:
- how to use it, should I write an application to include this static lib?
- why don't we include it in bionic unit test?

Besides these upon, I also see, together with posix test, there are some "duplicated" code in bionic unit test. For example, when there is `bionic/tests/headers/posix/arpa_inet_h.c`, I see another paired `bionic/tests/arpa_inet_test.cpp`. I'm not sure if the later covers the previous one. 

Thanks in adv.

**Comment by enh-google** [comment]
> why don't we include it in bionic unit test?

because _if it compiles_ it's already done its job. all these tests check is the claims in the POSIX spec about "<foo.h> contains a function void foo(int) and a struct foo containing a f_foo member of type int" or whatever. the _behavioral_ tests (that actually need to be run) are all in the main tests/ directory. ideally we'd have tests/api/ and tests/behavior/ or something, but since we started off with just behavioral tests, they got the top-level directory, and it's probably more disruptive (to link stability, say) than it's worth to move them now...

i've uploaded https://android-review.googlesource.com/c/platform/bionic/+/2582154 to explain this in-place.

**Comment by unicornx** [comment]
> > why don't we include it in bionic unit test?
> 
> because _if it compiles_ it's already done its job. all these tests check is the claims in the POSIX spec about "<foo.h> contains a function void foo(int) and a struct foo containing a f_foo member of type int" or whatever. the _behavioral_ tests (that actually need to be run) are all in the main tests/ directory. ideally we'd have tests/api/ and tests/behavior/ or something, but since we started off with just behavioral tests, they got the top-level directory, and it's probably more disruptive (to link stability, say) than it's worth to move them now...
> 
> i've uploaded https://android-review.googlesource.com/c/platform/bionic/+/2582154 to explain this in-place.

But I don't see "libbionic_tests_headers_posix" being compiled when I command `mmm bionic`, is it designed to be? If so, I would suggest it is compiled together with bionic target. What do you think?

**Comment by enh-google** [comment]
yeah, if you try `m`, `mm`, and `mmm`, you'll see that `m` doesn't build these, `mm` does, and `mmm` doesn't. aiui this is "working as intended", but it's one reason why i personally only use `mm`!
